version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pingvin
      POSTGRES_DB: myhelp
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  account-service:
    build:
      context: .
      dockerfile: services/account-service/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - db

  appointment-service:
    build:
      context: .
      dockerfile: services/appointment-service/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - db

  polyclinic-service:
    build:
      context: .
      dockerfile: services/polyclinic-service/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - db

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - account-service
      - appointment-service
      - polyclinic-service